### ISSUE TITLE
Согласовать взаимодействие фронтенда с бэкендом

### ISSUE THREAD

**Issue by mensch25** [mensch25/airBalloon_DOL#7]
Для взаимодействия понадобятся методы для передачи входных данных в бекенд и вывод результата алгоритма во фронтенд. Для статического метода возможно будет необходимо получать состояние графа (скорость и направление ветра в квадранте). Результат может выводиться как целиком, так и пошагово(динамически) [выбрать].

**Comment by iiurka** [comment]
- [ ] Возможность получения бэкендом значения скорости шара

- [ ] Возможность получения широты и долготы бэкендом по нажатию на карту
